// <auto-generated />
using System;
using Eventsocity.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eventsocity.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230106144313_SeedingTheEventsEntity")]
    partial class SeedingTheEventsEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eventsocity.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Sports",
                            City = "Egypt",
                            Date = new DateTime(2023, 1, 8, 14, 43, 11, 989, DateTimeKind.Utc).AddTicks(8621),
                            Description = "Let's play a padel game from 9 to 10 after 2 days, who is comming ! .. ",
                            Title = "Playing Padel",
                            Venue = "Nasr City, Nady El Shams"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Fun",
                            City = "Egypt",
                            Date = new DateTime(2023, 1, 7, 14, 43, 11, 989, DateTimeKind.Utc).AddTicks(8631),
                            Description = "I need to watch avatar 2 at cairo festival tommowrow and, anyone interested..",
                            Title = "Watching Avatar 2",
                            Venue = "Cairo Festival"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Sports",
                            City = "Egypt",
                            Date = new DateTime(2023, 1, 10, 14, 43, 11, 989, DateTimeKind.Utc).AddTicks(8633),
                            Description = "lets play 2 hours of football, i need 9 people",
                            Title = "Playing Footbal",
                            Venue = "Nady el Shams"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Social",
                            City = "Egypt",
                            Date = new DateTime(2023, 1, 6, 16, 43, 11, 989, DateTimeKind.Utc).AddTicks(8634),
                            Description = "I am having a break for 2 hours, anyone interested to have a lauch and a good talk, i need to eat in papa jones btw",
                            Title = "Having Launch",
                            Venue = "Papa jones"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
